version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo Current Branch is ${CURRENT_BRANCH}
      - restore_cache:
          key:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}
